export const hotelDefaults = {
  amenities: {
    wifi: false,
    powerBackup: false,
    parking: {
      twoWheeler: false,
      fourWheeler: false,
    },
    hotWater: false,
    laundryService: false,
    housekeeping: false,
    roomService: false,
    airConditioning: false,
    restaurant: false,
    bar: false,
    conferenceRoom: false,
    gym: false,
    swimmingPool: false,
    lift: false,
    cctv: false,
    security24x7: false,
    firstAidKit: false,
    fireExtinguisher: false,
    wheelChairAccess: false,
  },
  mealOptions: {
    includedMeals: {
      breakfast: false,
      lunch: false,
      dinner: false,
    },
    // Note: the schema requires at least one cuisine; using "Indian" as default.
    availableCuisines: "",
    specialDietaryMeals: {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      halal: false,
      kosher: false,
    },
    mealCharges: {
      breakfast: 0,
      lunch: 0,
      dinner: 0,
    },
    diningOptions: {
      inRoomDining: false,
      buffet: false,
      aLaCarte: false,
      commonDiningArea: false,
    },
  },
  dormitorySpecificDetails: {
    totalBeds: 0,
    bunkBedAvailability: false,
    lockerFacility: false,
    commonRoom: false,
    kitchenAccess: false,
    diningArea: false,
  },
  nearbyPlaces: {
    hospital: false,
    school: false,
    metro: false,
    mall: false,
    market: false,
    railway: false,
    airport: false,
    highway: false,
    busStation: false,
  },
  rules: {
    checkInTime: "",
    checkOutTime: "",
    smokingAllowed: false,
    alcoholAllowed: false,
    petsAllowed: false,
    quietHours: "",
    visitorPolicy: "",
    cancellationPolicy: "",
  },
  bookingOptions: {
    onlineBooking: false,
    walkIn: false,
    preBookingRequired: false,
    groupDiscounts: false,
    longStayDiscounts: false,
  },
  additionalFeatures: {
    childFriendly: false,
    coupleFriendly: false,
    seniorCitizenFriendly: false,
    localIDAccepted: false,
    pickupDropService: false,
    tourGuidance: false,
  },
};
